### ISSUE TITLE
Error wrong number of arguments in function set_door_code

### ISSUE THREAD

**Issue by jongrover** [aaronpk/Auto-AirBnB-Entry#1]
```
Warning: Missing argument 3 for set_door_code(), called in .../post.php on line 13 and defined in .../inc.php on line 30
```
In post.php set_door_code() is called with only 2 arguments $location and $code and fails to provide $index furthermore it appears as though $location is not used in this function. What is $index supposed to be?

To clarify if I visit index.php in a browser and select my location, insert my master_password that I created and type a new code and press the set code button it posts to post.php which throws the error you see above.

**Comment by aaronpk** [comment]
Thanks. The `$index` variable refers to the memory slot of the door lock, since some locks can support up to 16 codes. I usually have a few fixed codes defined in indexes 0-4, and use high numbers like 13-14 for the varying codes that this script uses. I'll push a fix.
