### ISSUE TITLE
Insecure API Keys and Codes

### ISSUE THREAD

**Issue by jongrover** [aaronpk/Auto-AirBnB-Entry#2]
In my browser if i go to config.yml I can see all the sensitive data such as the default code as well as password and api keys etc. I think there must be a better way to pass these details in your app in a more secure way. I think I will change them to be global vars in each PHP file instead so site visitors can't see them at least.

**Comment by aaronpk** [comment]
Yeah, I've blocked `config.yml` in my web server config, but it would probably be better to use a PHP config file for this. Feel free to rename it to `config.php` and use defines or variables and include that file from the other files.

**Comment by joshs85** [comment]
What are you using for an ICs parser?

**Comment by jongrover** [comment]
Thanks I'll make it PHP instead of YML.

**Comment by jongrover** [comment]
@joshs85 this thread is on security, but it looks like he is using JohnGRogg ICS-Parser this class is being included in my script via Composer, I had to type `composer install` to get it installed into my /vendor folder.
I think the source code for the library is from here: https://github.com/u01jmg3/ics-parser
